CREATE TABLE ITEM(
    Code VARCHAR(10) NOT NULL,
    Name VARCHAR(50),
    Spec VARCHAR(50),
    Quantity SMALLINT UNSIGNED,
    Unit VARCHAR(10),
    Stock SMALLINT UNSIGNED,
    Price INT UNSIGNED,
    Min_quantity SMALLINT UNSIGNED,
    Sc_id VARCHAR(10) NOT NULL,
    B_id VARCHAR(10) NOT NULL,
    PRIMARY KEY(Code)
);

CREATE TABLE SUPPLIER(
    S_id VARCHAR(10) NOT NULL,
    Name VARCHAR(50),
    PRIMARY KEY(S_id)
);

CREATE TABLE BRAND(
    B_id VARCHAR(10) NOT NULL,
    Name VARCHAR(50),
    S_id VARCHAR(10) NOT NULL,
    PRIMARY KEY(B_id),
    FOREIGN KEY(S_id) REFERENCES SUPPLIER(S_id)
    ON UPDATE CASCADE
);

CREATE TABLE L_CATEGORY(
    Lc_id VARCHAR(10) NOT NULL,
    Name VARCHAR(50),
    PRIMARY KEY(Lc_id)
);

CREATE TABLE M_CATEGORY(
    Mc_id VARCHAR(10) NOT NULL,
    Name VARCHAR(50),
    Lc_id VARCHAR(10) NOT NULL,
    PRIMARY KEY(Mc_id),
    FOREIGN KEY(Lc_id) REFERENCES L_CATEGORY(Lc_id)
    ON UPDATE CASCADE
);

CREATE TABLE S_CATEGORY(
    Sc_id VARCHAR(10) NOT NULL,
    Name VARCHAR(50),
    Mc_id VARCHAR(10) NOT NULL,
    PRIMARY KEY(Sc_id),
    FOREIGN KEY(Mc_id) REFERENCES M_CATEGORY(Mc_id)
    ON UPDATE CASCADE
);

ALTER TABLE ITEM ADD FOREIGN KEY (Sc_id) REFERENCES S_CATEGORY(Sc_id)
ON UPDATE CASCADE;

ALTER TABLE ITEM ADD FOREIGN KEY (B_id) REFERENCES BRAND(B_id)
ON UPDATE CASCADE;

CREATE TABLE CUSTOMER(
    C_id VARCHAR(10) NOT NULL,
    Username VARCHAR(20) NOT NULL,
    Password VARCHAR(30) NOT NULL,
    Address VARCHAR(200) NOT NULL,
    Tel VARCHAR(13) NOT NULL,
    Sex CHAR(1),
    Bdate DATE,
    Fname VARCHAR(30),
    Lname VARCHAR(30),
    Job VARCHAR(40),
    Type VARCHAR(6),
    PRIMARY KEY(C_id),
    UNIQUE(Username)
);

CREATE TABLE SHIPPINGCOMPANY(
    Sh_id VARCHAR(10) NOT NULL,
    Name VARCHAR(50),
    Tel VARCHAR(13),
    Region VARCHAR(20),
    PRIMARY KEY(Sh_id)
);

CREATE TABLE SHIPPINGORDER(
    So_id VARCHAR(10) NOT NULL,
    Address VARCHAR(200) NOT NULL,
    Rname VARCHAR(60),
    Rtel VARCHAR(13),
    Otime DATETIME,
    C_id VARCHAR(10) NOT NULL,
    Sh_id VARCHAR(10) NOT NULL,
    PRIMARY KEY(So_id),
    FOREIGN KEY(C_id) REFERENCES CUSTOMER(C_id)
    ON UPDATE CASCADE,
    FOREIGN KEY(Sh_id) REFERENCES SHIPPINGCOMPANY(Sh_id)
    ON UPDATE CASCADE
);

CREATE TABLE SHOPPINGBAG(
    C_id VARCHAR(10) NOT NULL,
    I_code VARCHAR(10) NOT NULL,
    Quantity SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY(C_id, I_code),
    FOREIGN KEY(C_id) REFERENCES CUSTOMER(C_id)
    ON UPDATE CASCADE,
    FOREIGN KEY(I_code) REFERENCES ITEM(Code)
    ON UPDATE CASCADE
);

CREATE TABLE ORDER_LIST(
    So_id VARCHAR(10) NOT NULL,
    I_code VARCHAR(10) NOT NULL,
    Quantity SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY(So_id, I_code),
    FOREIGN KEY(So_id) REFERENCES SHIPPINGORDER(So_id)
    ON UPDATE CASCADE,
    FOREIGN KEY(I_code) REFERENCES ITEM(Code)
    ON UPDATE CASCADE
);